name: MobWars
version: '1.0.1-SNAPSHOT'
main: org.ilmizeroth.MobWars.MobWars
api-version: '1.21'
author: IlmiZeroth
depend: [BetterModel]
commands:
  mwa:
    description: Main plugin command
    permission: mobwars.admin